language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - pip install . --quiet
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib --quiet --use-mirrors; fi"
  - pip install nose simplejson Flask-SQLAlchemy Flask-MongoEngine Flask-Peewee bcrypt coverage coveralls --quiet

services:
  - mongodb

script: nosetests --with-coverage --cover-package flask_security

after_script:
  - coveralls

branches:
  only:
    - develop
